import { Injectable } from '@angular/core';
import { HttpClient, HttpParams, HttpHeaders } from '@angular/common/http';

@Injectable()
export class OddsService {

  private key: string = `mjwIAnvnYc9olV6C7pfUp44HwjvpGuuM40Sc4p0k`;
  private host: string = `https://86qbtjzii8.execute-api.ap-southeast-2.amazonaws.com`;

  constructor(private http: HttpClient) { }

  getNflOdds() {
    let url = this.host + `/live_uk/odds/NFL`;

    const headers = new HttpHeaders().set('x-api-key', this.key);
    // return this.http.get(url, {headers});
    return {
      "success":true,
      "data":{
         "info":{
            "display_name":"NFL",
            "num_outcomes":"2",
            "check_dt":1505225723
         },
         "events":{
            "Cincinnati Bengals_Houston Texans":{
               "sport":"NFL",
               "sport_display":"NFL",
               "participants":[
                  "Cincinnati Bengals",
                  "Houston Texans"
               ],
               "commence":"1505435100",
               "status":"Pending",
               "sites":{
                  "williamhill":{
                     "odds":{
                        "h2h":[
                           "1.42",
                           "2.90"
                        ]
                     },
                     "last_update":1505225699
                  },
                  "pinnacle":{
                     "odds":{
                        "h2h":[
                           "1.44",
                           "3.01"
                        ]
                     },
                     "last_update":1505225700
                  },
                  "betfair":{
                     "odds":{
                        "h2h":[
                           "1.42",
                           "2.88"
                        ],
                        "h2h_lay":[
                           "1.49",
                           "3.40"
                        ]
                     },
                     "last_update":1505225700
                  },
                  "ladbrokes":{
                     "odds":{
                        "h2h":[
                           "1.40",
                           "3.00"
                        ]
                     },
                     "last_update":1505225706
                  },
                  "tab":{
                     "odds":{
                        "h2h":[
                           "1.45",
                           "2.75"
                        ]
                     },
                     "last_update":1505225708
                  },
                  "ubet":{
                     "odds":{
                        "h2h":[
                           "1.45",
                           "2.75"
                        ]
                     },
                     "last_update":1505225713
                  },
                  "unibet":{
                     "odds":{
                        "h2h":[
   
                        ]
                     },
                     "last_update":1505225716
                  },
                  "crownbet":{
                     "odds":{
                        "h2h":[
                           "1.43",
                           "2.90"
                        ]
                     },
                     "last_update":1505225716
                  },
                  "sportsbet":{
                     "odds":{
                        "h2h":[
                           "1.42",
                           "2.96"
                        ]
                     },
                     "last_update":1505225720
                  },
                  "luxbet":{
                     "odds":{
                        "h2h":[
                           "1.43",
                           "2.80"
                        ]
                     },
                     "last_update":1505225722
                  }
               }
            },
            "Arizona Cardinals_Indianapolis Colts":{
               "sport":"NFL",
               "sport_display":"NFL",
               "participants":[
                  "Arizona Cardinals",
                  "Indianapolis Colts"
               ],
               "commence":"1505667600",
               "status":"Pending",
               "sites":{
                  "williamhill":{
                     "odds":{
                        "h2h":[
                           "1.28",
                           "3.80"
                        ]
                     },
                     "last_update":1505225699
                  },
                  "pinnacle":{
                     "odds":{
                        "h2h":[
                           "1.31",
                           "3.85"
                        ]
                     },
                     "last_update":1505225700
                  },
                  "betfair":{
                     "odds":{
                        "h2h":[
                           "1.31",
                           "3.61"
                        ],
                        "h2h_lay":[
                           "1.36",
                           "4.00"
                        ]
                     },
                     "last_update":1505225700
                  },
                  "ladbrokes":{
                     "odds":{
                        "h2h":[
                           "1.29",
                           "3.75"
                        ]
                     },
                     "last_update":1505225706
                  },
                  "tab":{
                     "odds":{
                        "h2h":[
                           "1.28",
                           "3.75"
                        ]
                     },
                     "last_update":1505225708
                  },
                  "ubet":{
                     "odds":{
                        "h2h":[
                           "1.28",
                           "3.75"
                        ]
                     },
                     "last_update":1505225713
                  },
                  "unibet":{
                     "odds":{
                        "h2h":[
                           "1.30",
                           "3.65"
                        ]
                     },
                     "last_update":1505225716
                  },
                  "crownbet":{
                     "odds":{
                        "h2h":[
                           "1.29",
                           "3.75"
                        ]
                     },
                     "last_update":1505225716
                  },
                  "sportsbet":{
                     "odds":{
                        "h2h":[
                           "1.29",
                           "3.75"
                        ]
                     },
                     "last_update":1505225720
                  },
                  "luxbet":{
                     "odds":{
                        "h2h":[
                           "1.28",
                           "3.65"
                        ]
                     },
                     "last_update":1505225722
                  }
               }
            },
            "Baltimore Ravens_Cleveland Browns":{
               "sport":"NFL",
               "sport_display":"NFL",
               "participants":[
                  "Baltimore Ravens",
                  "Cleveland Browns"
               ],
               "commence":"1505667600",
               "status":"Pending",
               "sites":{
                  "williamhill":{
                     "odds":{
                        "h2h":[
                           "1.28",
                           "3.80"
                        ]
                     },
                     "last_update":1505225699
                  },
                  "pinnacle":{
                     "odds":{
                        "h2h":[
                           "1.31",
                           "3.85"
                        ]
                     },
                     "last_update":1505225700
                  },
                  "betfair":{
                     "odds":{
                        "h2h":[
                           "1.28",
                           "3.61"
                        ],
                        "h2h_lay":[
                           "1.37",
                           "4.50"
                        ]
                     },
                     "last_update":1505225700
                  },
                  "ladbrokes":{
                     "odds":{
                        "h2h":[
                           "1.29",
                           "3.80"
                        ]
                     },
                     "last_update":1505225706
                  },
                  "tab":{
                     "odds":{
                        "h2h":[
                           "1.28",
                           "3.75"
                        ]
                     },
                     "last_update":1505225708
                  },
                  "ubet":{
                     "odds":{
                        "h2h":[
                           "1.28",
                           "3.75"
                        ]
                     },
                     "last_update":1505225713
                  },
                  "unibet":{
                     "odds":{
                        "h2h":[
                           "1.30",
                           "3.70"
                        ]
                     },
                     "last_update":1505225716
                  },
                  "crownbet":{
                     "odds":{
                        "h2h":[
                           "1.29",
                           "3.75"
                        ]
                     },
                     "last_update":1505225716
                  },
                  "sportsbet":{
                     "odds":{
                        "h2h":[
                           "1.29",
                           "3.75"
                        ]
                     },
                     "last_update":1505225720
                  },
                  "luxbet":{
                     "odds":{
                        "h2h":[
                           "1.28",
                           "3.65"
                        ]
                     },
                     "last_update":1505225722
                  }
               }
            },
            "Buffalo Bills_Carolina Panthers":{
               "sport":"NFL",
               "sport_display":"NFL",
               "participants":[
                  "Buffalo Bills",
                  "Carolina Panthers"
               ],
               "commence":"1505667600",
               "status":"Pending",
               "sites":{
                  "williamhill":{
                     "odds":{
                        "h2h":[
                           "3.60",
                           "1.30"
                        ]
                     },
                     "last_update":1505225699
                  },
                  "pinnacle":{
                     "odds":{
                        "h2h":[
                           "3.64",
                           "1.33"
                        ]
                     },
                     "last_update":1505225700
                  },
                  "betfair":{
                     "odds":{
                        "h2h":[
                           "3.42",
                           "1.29"
                        ],
                        "h2h_lay":[
                           "4.30",
                           "1.40"
                        ]
                     },
                     "last_update":1505225700
                  },
                  "ladbrokes":{
                     "odds":{
                        "h2h":[
                           "3.60",
                           "1.30"
                        ]
                     },
                     "last_update":1505225706
                  },
                  "tab":{
                     "odds":{
                        "h2h":[
                           "3.50",
                           "1.30"
                        ]
                     },
                     "last_update":1505225708
                  },
                  "ubet":{
                     "odds":{
                        "h2h":[
                           "3.55",
                           "1.30"
                        ]
                     },
                     "last_update":1505225713
                  },
                  "unibet":{
                     "odds":{
                        "h2h":[
                           "3.75",
                           "1.29"
                        ]
                     },
                     "last_update":1505225716
                  },
                  "crownbet":{
                     "odds":{
                        "h2h":[
                           "3.50",
                           "1.31"
                        ]
                     },
                     "last_update":1505225716
                  },
                  "sportsbet":{
                     "odds":{
                        "h2h":[
                           "3.60",
                           "1.31"
                        ]
                     },
                     "last_update":1505225720
                  },
                  "luxbet":{
                     "odds":{
                        "h2h":[
                           "3.50",
                           "1.30"
                        ]
                     },
                     "last_update":1505225722
                  }
               }
            },
            "Chicago Bears_Tampa Bay Buccaneers":{
               "sport":"NFL",
               "sport_display":"NFL",
               "participants":[
                  "Chicago Bears",
                  "Tampa Bay Buccaneers"
               ],
               "commence":"1505667600",
               "status":"Pending",
               "sites":{
                  "williamhill":{
                     "odds":{
                        "h2h":[
                           "3.40",
                           "1.33"
                        ]
                     },
                     "last_update":1505225699
                  },
                  "pinnacle":{
                     "odds":{
                        "h2h":[
                           "3.52",
                           "1.35"
                        ]
                     },
                     "last_update":1505225700
                  },
                  "betfair":{
                     "odds":{
                        "h2h":[
                           "3.28",
                           "1.31"
                        ],
                        "h2h_lay":[
                           "4.10",
                           "1.42"
                        ]
                     },
                     "last_update":1505225700
                  },
                  "ladbrokes":{
                     "odds":{
                        "h2h":[
                           "3.40",
                           "1.33"
                        ]
                     },
                     "last_update":1505225706
                  },
                  "tab":{
                     "odds":{
                        "h2h":[
                           "3.35",
                           "1.33"
                        ]
                     },
                     "last_update":1505225708
                  },
                  "ubet":{
                     "odds":{
                        "h2h":[
                           "3.45",
                           "1.32"
                        ]
                     },
                     "last_update":1505225713
                  },
                  "unibet":{
                     "odds":{
                        "h2h":[
                           "3.25",
                           "1.37"
                        ]
                     },
                     "last_update":1505225716
                  },
                  "crownbet":{
                     "odds":{
                        "h2h":[
                           "3.40",
                           "1.33"
                        ]
                     },
                     "last_update":1505225716
                  },
                  "sportsbet":{
                     "odds":{
                        "h2h":[
                           "3.47",
                           "1.33"
                        ]
                     },
                     "last_update":1505225720
                  },
                  "luxbet":{
                     "odds":{
                        "h2h":[
                           "3.30",
                           "1.33"
                        ]
                     },
                     "last_update":1505225722
                  }
               }
            },
            "Jacksonville Jaguars_Tennessee Titans":{
               "sport":"NFL",
               "sport_display":"NFL",
               "participants":[
                  "Jacksonville Jaguars",
                  "Tennessee Titans"
               ],
               "commence":"1505667600",
               "status":"Pending",
               "sites":{
                  "williamhill":{
                     "odds":{
                        "h2h":[
                           "2.05",
                           "1.80"
                        ]
                     },
                     "last_update":1505225699
                  },
                  "pinnacle":{
                     "odds":{
                        "h2h":[
                           "2.11",
                           "1.81"
                        ]
                     },
                     "last_update":1505225700
                  },
                  "betfair":{
                     "odds":{
                        "h2h":[
                           "2.03",
                           "1.73"
                        ],
                        "h2h_lay":[
                           "2.30",
                           "1.93"
                        ]
                     },
                     "last_update":1505225700
                  },
                  "ladbrokes":{
                     "odds":{
                        "h2h":[
                           "2.05",
                           "1.80"
                        ]
                     },
                     "last_update":1505225706
                  },
                  "tab":{
                     "odds":{
                        "h2h":[
                           "2.00",
                           "1.80"
                        ]
                     },
                     "last_update":1505225708
                  },
                  "ubet":{
                     "odds":{
                        "h2h":[
                           "2.05",
                           "1.77"
                        ]
                     },
                     "last_update":1505225713
                  },
                  "unibet":{
                     "odds":{
                        "h2h":[
                           "2.02",
                           "1.83"
                        ]
                     },
                     "last_update":1505225716
                  },
                  "crownbet":{
                     "odds":{
                        "h2h":[
                           "2.07",
                           "1.79"
                        ]
                     },
                     "last_update":1505225716
                  },
                  "sportsbet":{
                     "odds":{
                        "h2h":[
                           "2.07",
                           "1.79"
                        ]
                     },
                     "last_update":1505225720
                  },
                  "luxbet":{
                     "odds":{
                        "h2h":[
                           "2.02",
                           "1.78"
                        ]
                     },
                     "last_update":1505225722
                  }
               }
            },
            "Kansas City Chiefs_Philadelphia Eagles":{
               "sport":"NFL",
               "sport_display":"NFL",
               "participants":[
                  "Kansas City Chiefs",
                  "Philadelphia Eagles"
               ],
               "commence":"1505667600",
               "status":"Pending",
               "sites":{
                  "williamhill":{
                     "odds":{
                        "h2h":[
                           "1.45",
                           "2.80"
                        ]
                     },
                     "last_update":1505225699
                  },
                  "pinnacle":{
                     "odds":{
                        "h2h":[
                           "1.48",
                           "2.86"
                        ]
                     },
                     "last_update":1505225700
                  },
                  "betfair":{
                     "odds":{
                        "h2h":[
                           "1.44",
                           "2.69"
                        ],
                        "h2h_lay":[
                           "1.57",
                           "3.20"
                        ]
                     },
                     "last_update":1505225700
                  },
                  "ladbrokes":{
                     "odds":{
                        "h2h":[
                           "1.44",
                           "2.88"
                        ]
                     },
                     "last_update":1505225706
                  },
                  "tab":{
                     "odds":{
                        "h2h":[
                           "1.45",
                           "2.75"
                        ]
                     },
                     "last_update":1505225708
                  },
                  "ubet":{
                     "odds":{
                        "h2h":[
                           "1.45",
                           "2.75"
                        ]
                     },
                     "last_update":1505225713
                  },
                  "unibet":{
                     "odds":{
                        "h2h":[
                           "1.53",
                           "2.55"
                        ]
                     },
                     "last_update":1505225716
                  },
                  "crownbet":{
                     "odds":{
                        "h2h":[
                           "1.46",
                           "2.80"
                        ]
                     },
                     "last_update":1505225716
                  },
                  "sportsbet":{
                     "odds":{
                        "h2h":[
                           "1.46",
                           "2.81"
                        ]
                     },
                     "last_update":1505225720
                  },
                  "luxbet":{
                     "odds":{
                        "h2h":[
                           "1.46",
                           "2.70"
                        ]
                     },
                     "last_update":1505225722
                  }
               }
            },
            "New England Patriots_New Orleans Saints":{
               "sport":"NFL",
               "sport_display":"NFL",
               "participants":[
                  "New England Patriots",
                  "New Orleans Saints"
               ],
               "commence":"1505667600",
               "status":"Pending",
               "sites":{
                  "pinnacle":{
                     "odds":{
                        "h2h":[
   
                        ]
                     },
                     "last_update":1505225700
                  },
                  "betfair":{
                     "odds":{
                        "h2h":[
                           "1.41",
                           "2.90"
                        ],
                        "h2h_lay":[
                           "1.50",
                           "3.35"
                        ]
                     },
                     "last_update":1505225700
                  },
                  "ladbrokes":{
                     "odds":{
                        "h2h":[
                           "1.00",
                           "1.00"
                        ]
                     },
                     "last_update":1505225706
                  },
                  "sportsbet":{
                     "odds":{
                        "h2h":[
                           "1.47",
                           "2.77"
                        ]
                     },
                     "last_update":1505225720
                  },
                  "luxbet":{
                     "odds":{
                        "h2h":[
                           "1.39",
                           "3.00"
                        ]
                     },
                     "last_update":1505225722
                  }
               }
            },
            "New York Jets_Oakland Raiders":{
               "sport":"NFL",
               "sport_display":"NFL",
               "participants":[
                  "New York Jets",
                  "Oakland Raiders"
               ],
               "commence":"1505678700",
               "status":"Pending",
               "sites":{
                  "williamhill":{
                     "odds":{
                        "h2h":[
                           "7.00",
                           "1.11"
                        ]
                     },
                     "last_update":1505225699
                  },
                  "pinnacle":{
                     "odds":{
                        "h2h":[
                           "7.38",
                           "1.13"
                        ]
                     },
                     "last_update":1505225700
                  },
                  "betfair":{
                     "odds":{
                        "h2h":[
                           "5.75",
                           "1.09"
                        ],
                        "h2h_lay":[
                           "21.00",
                           "1.18"
                        ]
                     },
                     "last_update":1505225700
                  },
                  "ladbrokes":{
                     "odds":{
                        "h2h":[
                           "7.50",
                           "1.10"
                        ]
                     },
                     "last_update":1505225706
                  },
                  "tab":{
                     "odds":{
                        "h2h":[
                           "6.00",
                           "1.13"
                        ]
                     },
                     "last_update":1505225708
                  },
                  "ubet":{
                     "odds":{
                        "h2h":[
                           "7.00",
                           "1.10"
                        ]
                     },
                     "last_update":1505225713
                  },
                  "unibet":{
                     "odds":{
                        "h2h":[
                           "7.50",
                           "1.11"
                        ]
                     },
                     "last_update":1505225716
                  },
                  "crownbet":{
                     "odds":{
                        "h2h":[
                           "7.60",
                           "1.10"
                        ]
                     },
                     "last_update":1505225716
                  },
                  "sportsbet":{
                     "odds":{
                        "h2h":[
                           "7.00",
                           "1.11"
                        ]
                     },
                     "last_update":1505225720
                  },
                  "luxbet":{
                     "odds":{
                        "h2h":[
                           "6.50",
                           "1.11"
                        ]
                     },
                     "last_update":1505225722
                  }
               }
            },
            "Los Angeles Rams_Washington Redskins":{
               "sport":"NFL",
               "sport_display":"NFL",
               "participants":[
                  "Los Angeles Rams",
                  "Washington Redskins"
               ],
               "commence":"1505679900",
               "status":"Pending",
               "sites":{
                  "williamhill":{
                     "odds":{
                        "h2h":[
                           "1.74",
                           "2.13"
                        ]
                     },
                     "last_update":1505225699
                  },
                  "pinnacle":{
                     "odds":{
                        "h2h":[
                           "1.74",
                           "2.23"
                        ]
                     },
                     "last_update":1505225700
                  },
                  "betfair":{
                     "odds":{
                        "h2h":[
                           "1.66",
                           "2.12"
                        ],
                        "h2h_lay":[
                           "1.85",
                           "2.46"
                        ]
                     },
                     "last_update":1505225700
                  },
                  "ladbrokes":{
                     "odds":{
                        "h2h":[
                           "1.73",
                           "2.15"
                        ]
                     },
                     "last_update":1505225706
                  },
                  "tab":{
                     "odds":{
                        "h2h":[
                           "1.70",
                           "2.15"
                        ]
                     },
                     "last_update":1505225708
                  },
                  "ubet":{
                     "odds":{
                        "h2h":[
                           "1.70",
                           "2.15"
                        ]
                     },
                     "last_update":1505225713
                  },
                  "unibet":{
                     "odds":{
                        "h2h":[
                           "1.74",
                           "2.15"
                        ]
                     },
                     "last_update":1505225716
                  },
                  "crownbet":{
                     "odds":{
                        "h2h":[
                           "1.74",
                           "2.14"
                        ]
                     },
                     "last_update":1505225716
                  },
                  "sportsbet":{
                     "odds":{
                        "h2h":[
                           "1.71",
                           "2.19"
                        ]
                     },
                     "last_update":1505225720
                  },
                  "luxbet":{
                     "odds":{
                        "h2h":[
                           "1.70",
                           "2.15"
                        ]
                     },
                     "last_update":1505225722
                  }
               }
            },
            "San Francisco 49ers_Seattle Seahawks":{
               "sport":"NFL",
               "sport_display":"NFL",
               "participants":[
                  "San Francisco 49ers",
                  "Seattle Seahawks"
               ],
               "commence":"1505679900",
               "status":"Pending",
               "sites":{
                  "williamhill":{
                     "odds":{
                        "h2h":[
                           "6.00",
                           "1.14"
                        ]
                     },
                     "last_update":1505225699
                  },
                  "pinnacle":{
                     "odds":{
                        "h2h":[
                           "6.20",
                           "1.16"
                        ]
                     },
                     "last_update":1505225700
                  },
                  "betfair":{
                     "odds":{
                        "h2h":[
                           "5.28",
                           "1.11"
                        ],
                        "h2h_lay":[
                           "9.40",
                           "1.21"
                        ]
                     },
                     "last_update":1505225700
                  },
                  "ladbrokes":{
                     "odds":{
                        "h2h":[
                           "6.00",
                           "1.14"
                        ]
                     },
                     "last_update":1505225706
                  },
                  "tab":{
                     "odds":{
                        "h2h":[
                           "5.50",
                           "1.15"
                        ]
                     },
                     "last_update":1505225708
                  },
                  "ubet":{
                     "odds":{
                        "h2h":[
                           "6.50",
                           "1.11"
                        ]
                     },
                     "last_update":1505225713
                  },
                  "unibet":{
                     "odds":{
                        "h2h":[
                           "6.00",
                           "1.15"
                        ]
                     },
                     "last_update":1505225716
                  },
                  "crownbet":{
                     "odds":{
                        "h2h":[
                           "6.00",
                           "1.14"
                        ]
                     },
                     "last_update":1505225716
                  },
                  "sportsbet":{
                     "odds":{
                        "h2h":[
                           "6.10",
                           "1.14"
                        ]
                     },
                     "last_update":1505225720
                  },
                  "luxbet":{
                     "odds":{
                        "h2h":[
                           "5.85",
                           "1.13"
                        ]
                     },
                     "last_update":1505225722
                  }
               }
            },
            "Atlanta Falcons_Green Bay Packers":{
               "sport":"NFL",
               "sport_display":"NFL",
               "participants":[
                  "Atlanta Falcons",
                  "Green Bay Packers"
               ],
               "commence":"1505694600",
               "status":"Pending",
               "sites":{
                  "williamhill":{
                     "odds":{
                        "h2h":[
                           "1.68",
                           "2.22"
                        ]
                     },
                     "last_update":1505225699
                  },
                  "pinnacle":{
                     "odds":{
                        "h2h":[
                           "1.70",
                           "2.29"
                        ]
                     },
                     "last_update":1505225700
                  },
                  "betfair":{
                     "odds":{
                        "h2h":[
                           "1.71",
                           "2.18"
                        ],
                        "h2h_lay":[
                           "1.80",
                           "2.34"
                        ]
                     },
                     "last_update":1505225700
                  },
                  "ladbrokes":{
                     "odds":{
                        "h2h":[
                           "1.67",
                           "2.25"
                        ]
                     },
                     "last_update":1505225706
                  },
                  "tab":{
                     "odds":{
                        "h2h":[
                           "1.65",
                           "2.25"
                        ]
                     },
                     "last_update":1505225708
                  },
                  "ubet":{
                     "odds":{
                        "h2h":[
                           "1.65",
                           "2.25"
                        ]
                     },
                     "last_update":1505225713
                  },
                  "unibet":{
                     "odds":{
                        "h2h":[
                           "1.70",
                           "2.23"
                        ]
                     },
                     "last_update":1505225716
                  },
                  "crownbet":{
                     "odds":{
                        "h2h":[
                           "1.68",
                           "2.24"
                        ]
                     },
                     "last_update":1505225716
                  },
                  "sportsbet":{
                     "odds":{
                        "h2h":[
                           "1.68",
                           "2.25"
                        ]
                     },
                     "last_update":1505225720
                  },
                  "luxbet":{
                     "odds":{
                        "h2h":[
                           "1.66",
                           "2.22"
                        ]
                     },
                     "last_update":1505225722
                  }
               }
            }
         }
      }
   };
    //return {"success":true,"data":{"info":{"display_name":"NFL","num_outcomes":"2","check_dt":1505225724},"events":{"Cincinnati Bengals_Houston Texans":{"sport":"NFL","sport_display":"NFL","participants":["Cincinnati Bengals","Houston Texans"],"commence":"1505435100","status":"Pending","sites":{"tonybet":{"odds":{"h2h":["1.41","2.95"]},"last_update":1505225691},"williamhill":{"odds":{"h2h":["1.42","2.90"]},"last_update":1505225699},"pinnacle":{"odds":{"h2h":["1.44","3.01"]},"last_update":1505225700},"betfair":{"odds":{"h2h":["1.42","2.88"],"h2h_lay":["1.49","3.40"]},"last_update":1505225700},"ladbrokes":{"odds":{"h2h":["1.40","3.00"]},"last_update":1505225706},"unibet":{"odds":{"h2h":[]},"last_update":1505225716},"skybet":{"odds":{"h2h":["1.40","2.88"]},"last_update":1505225717}}},"Arizona Cardinals_Indianapolis Colts":{"sport":"NFL","sport_display":"NFL","participants":["Arizona Cardinals","Indianapolis Colts"],"commence":"1505667600","status":"Pending","sites":{"tonybet":{"odds":{"h2h":["1.27","3.75"]},"last_update":1505225692},"williamhill":{"odds":{"h2h":["1.28","3.80"]},"last_update":1505225699},"pinnacle":{"odds":{"h2h":["1.31","3.85"]},"last_update":1505225700},"betfair":{"odds":{"h2h":["1.31","3.61"],"h2h_lay":["1.36","4.00"]},"last_update":1505225700},"ladbrokes":{"odds":{"h2h":["1.29","3.75"]},"last_update":1505225706},"unibet":{"odds":{"h2h":["1.30","3.65"]},"last_update":1505225716},"skybet":{"odds":{"h2h":["1.29","3.75"]},"last_update":1505225717}}},"Baltimore Ravens_Cleveland Browns":{"sport":"NFL","sport_display":"NFL","participants":["Baltimore Ravens","Cleveland Browns"],"commence":"1505667600","status":"Pending","sites":{"tonybet":{"odds":{"h2h":["1.27","3.75"]},"last_update":1505225692},"williamhill":{"odds":{"h2h":["1.28","3.80"]},"last_update":1505225699},"pinnacle":{"odds":{"h2h":["1.31","3.85"]},"last_update":1505225700},"betfair":{"odds":{"h2h":["1.28","3.61"],"h2h_lay":["1.37","4.50"]},"last_update":1505225700},"ladbrokes":{"odds":{"h2h":["1.29","3.80"]},"last_update":1505225706},"unibet":{"odds":{"h2h":["1.30","3.70"]},"last_update":1505225716},"skybet":{"odds":{"h2h":["1.29","3.75"]},"last_update":1505225717}}},"Buffalo Bills_Carolina Panthers":{"sport":"NFL","sport_display":"NFL","participants":["Buffalo Bills","Carolina Panthers"],"commence":"1505667600","status":"Pending","sites":{"tonybet":{"odds":{"h2h":["3.55","1.30"]},"last_update":1505225691},"williamhill":{"odds":{"h2h":["3.60","1.30"]},"last_update":1505225699},"pinnacle":{"odds":{"h2h":["3.64","1.33"]},"last_update":1505225700},"betfair":{"odds":{"h2h":["3.42","1.29"],"h2h_lay":["4.30","1.40"]},"last_update":1505225700},"ladbrokes":{"odds":{"h2h":["3.60","1.30"]},"last_update":1505225706},"unibet":{"odds":{"h2h":["3.75","1.29"]},"last_update":1505225716},"skybet":{"odds":{"h2h":["3.50","1.33"]},"last_update":1505225717}}},"Chicago Bears_Tampa Bay Buccaneers":{"sport":"NFL","sport_display":"NFL","participants":["Chicago Bears","Tampa Bay Buccaneers"],"commence":"1505667600","status":"Pending","sites":{"tonybet":{"odds":{"h2h":["3.45","1.31"]},"last_update":1505225691},"williamhill":{"odds":{"h2h":["3.40","1.33"]},"last_update":1505225699},"pinnacle":{"odds":{"h2h":["3.52","1.35"]},"last_update":1505225700},"betfair":{"odds":{"h2h":["3.28","1.31"],"h2h_lay":["4.10","1.42"]},"last_update":1505225700},"ladbrokes":{"odds":{"h2h":["3.40","1.33"]},"last_update":1505225706},"unibet":{"odds":{"h2h":["3.25","1.37"]},"last_update":1505225716},"skybet":{"odds":{"h2h":["3.50","1.33"]},"last_update":1505225717}}},"Jacksonville Jaguars_Tennessee Titans":{"sport":"NFL","sport_display":"NFL","participants":["Jacksonville Jaguars","Tennessee Titans"],"commence":"1505667600","status":"Pending","sites":{"tonybet":{"odds":{"h2h":["2.05","1.77"]},"last_update":1505225692},"williamhill":{"odds":{"h2h":["2.05","1.80"]},"last_update":1505225699},"pinnacle":{"odds":{"h2h":["2.11","1.81"]},"last_update":1505225700},"betfair":{"odds":{"h2h":["2.03","1.73"],"h2h_lay":["2.30","1.93"]},"last_update":1505225700},"ladbrokes":{"odds":{"h2h":["2.05","1.80"]},"last_update":1505225706},"unibet":{"odds":{"h2h":["2.02","1.83"]},"last_update":1505225716},"skybet":{"odds":{"h2h":["2.10","1.80"]},"last_update":1505225717}}},"Kansas City Chiefs_Philadelphia Eagles":{"sport":"NFL","sport_display":"NFL","participants":["Kansas City Chiefs","Philadelphia Eagles"],"commence":"1505667600","status":"Pending","sites":{"tonybet":{"odds":{"h2h":["1.44","2.80"]},"last_update":1505225692},"williamhill":{"odds":{"h2h":["1.45","2.80"]},"last_update":1505225699},"pinnacle":{"odds":{"h2h":["1.48","2.86"]},"last_update":1505225700},"betfair":{"odds":{"h2h":["1.44","2.69"],"h2h_lay":["1.57","3.20"]},"last_update":1505225700},"ladbrokes":{"odds":{"h2h":["1.44","2.88"]},"last_update":1505225706},"unibet":{"odds":{"h2h":["1.53","2.55"]},"last_update":1505225716},"skybet":{"odds":{"h2h":["1.44","2.88"]},"last_update":1505225717}}},"New England Patriots_New Orleans Saints":{"sport":"NFL","sport_display":"NFL","participants":["New England Patriots","New Orleans Saints"],"commence":"1505667600","status":"Pending","sites":{"pinnacle":{"odds":{"h2h":[]},"last_update":1505225700},"betfair":{"odds":{"h2h":["1.41","2.90"],"h2h_lay":["1.50","3.35"]},"last_update":1505225700},"ladbrokes":{"odds":{"h2h":["1.00","1.00"]},"last_update":1505225706}}},"New York Jets_Oakland Raiders":{"sport":"NFL","sport_display":"NFL","participants":["New York Jets","Oakland Raiders"],"commence":"1505678700","status":"Pending","sites":{"tonybet":{"odds":{"h2h":["7.20","1.09"]},"last_update":1505225692},"williamhill":{"odds":{"h2h":["7.00","1.11"]},"last_update":1505225699},"pinnacle":{"odds":{"h2h":["7.38","1.13"]},"last_update":1505225700},"betfair":{"odds":{"h2h":["5.75","1.09"],"h2h_lay":["21.00","1.18"]},"last_update":1505225700},"ladbrokes":{"odds":{"h2h":["7.50","1.10"]},"last_update":1505225706},"unibet":{"odds":{"h2h":["7.50","1.11"]},"last_update":1505225716},"skybet":{"odds":{"h2h":["8.00","1.10"]},"last_update":1505225717}}},"Los Angeles Rams_Washington Redskins":{"sport":"NFL","sport_display":"NFL","participants":["Los Angeles Rams","Washington Redskins"],"commence":"1505679900","status":"Pending","sites":{"tonybet":{"odds":{"h2h":["1.72","2.10"]},"last_update":1505225692},"williamhill":{"odds":{"h2h":["1.74","2.13"]},"last_update":1505225699},"pinnacle":{"odds":{"h2h":["1.74","2.23"]},"last_update":1505225700},"betfair":{"odds":{"h2h":["1.66","2.12"],"h2h_lay":["1.85","2.46"]},"last_update":1505225700},"ladbrokes":{"odds":{"h2h":["1.73","2.15"]},"last_update":1505225706},"unibet":{"odds":{"h2h":["1.74","2.15"]},"last_update":1505225716},"skybet":{"odds":{"h2h":["1.73","2.10"]},"last_update":1505225717}}},"San Francisco 49ers_Seattle Seahawks":{"sport":"NFL","sport_display":"NFL","participants":["San Francisco 49ers","Seattle Seahawks"],"commence":"1505679900","status":"Pending","sites":{"tonybet":{"odds":{"h2h":["6.05","1.13"]},"last_update":1505225692},"williamhill":{"odds":{"h2h":["6.00","1.14"]},"last_update":1505225699},"pinnacle":{"odds":{"h2h":["6.20","1.16"]},"last_update":1505225700},"betfair":{"odds":{"h2h":["5.28","1.11"],"h2h_lay":["9.40","1.21"]},"last_update":1505225700},"ladbrokes":{"odds":{"h2h":["6.00","1.14"]},"last_update":1505225706},"unibet":{"odds":{"h2h":["6.00","1.15"]},"last_update":1505225716},"skybet":{"odds":{"h2h":["6.00","1.13"]},"last_update":1505225717}}},"Atlanta Falcons_Green Bay Packers":{"sport":"NFL","sport_display":"NFL","participants":["Atlanta Falcons","Green Bay Packers"],"commence":"1505694600","status":"Pending","sites":{"tonybet":{"odds":{"h2h":["1.65","2.25"]},"last_update":1505225692},"williamhill":{"odds":{"h2h":["1.68","2.22"]},"last_update":1505225699},"pinnacle":{"odds":{"h2h":["1.70","2.29"]},"last_update":1505225700},"betfair":{"odds":{"h2h":["1.71","2.18"],"h2h_lay":["1.80","2.34"]},"last_update":1505225700},"ladbrokes":{"odds":{"h2h":["1.67","2.25"]},"last_update":1505225706},"unibet":{"odds":{"h2h":["1.70","2.23"]},"last_update":1505225716},"skybet":{"odds":{"h2h":["1.67","2.25"]},"last_update":1505225717}}}}}};
  }

}
